In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/n2d-custom-4-8192'
SCENARIO = 'n2d-custom-4-8192'
NETWORK_LATENCY = 0.030171

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

1.781784

In [5]:
print(dfs[1][1].latency.to_string(index=False))

2.055313
1.508255

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,1.818878,1.865487,0.340187,1.774229,1.683689,1.773043,1.942382,1.645176,1.450114,1.597811
2,1.594591,1.781784,0.895930,1.084321,1.333608,1.457357,1.388608,0.874219,1.376299,1.199504
4,1.566034,0.982293,1.834712,1.398068,0.581530,1.216531,1.433242,1.585144,1.296361,1.609443
8,3.600461,2.325249,4.381365,3.981649,2.619533,2.684270,3.973255,2.821775,2.616523,1.647714
16,6.070597,6.216432,8.051401,6.143053,6.976888,9.148446,4.688471,5.479102,8.670044,7.581527
32,14.284547,15.890871,12.745114,12.058350,11.734377,12.351435,11.509042,12.007886,15.118814,11.820013
64,26.169884,23.380202,24.479907,25.020767,29.250873,24.413303,26.618234,24.140092,29.887081,23.485432
128,45.085994,43.842056,42.346672,43.581206,42.040131,44.284234,45.973544,43.042648,40.050578,41.957571
256,54.924063,54.919283,55.750773,55.554535,54.661618,56.677385,56.807124,54.860864,53.505751,55.877054
512,62.518541,59.372659,67.374803,67.084971,60.709052,60.879291,60.384401,59.283485,66.029919,59.183239

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,1.788707,1.835316,0.310016,1.744058,1.653518,1.742872,1.912211,1.615005,1.419943,1.567640
2,1.564420,1.751613,0.865759,1.054150,1.303438,1.427186,1.358437,0.844048,1.346128,1.169333
4,1.535863,0.952122,1.804542,1.367897,0.551359,1.186360,1.403071,1.554973,1.266190,1.579272
8,3.570290,2.295078,4.351193,3.951478,2.589362,2.654099,3.943084,2.791604,2.586352,1.617543
16,6.040426,6.186261,8.021230,6.112882,6.946717,9.118275,4.658300,5.448931,8.639873,7.551356
32,14.254376,15.860700,12.714943,12.028179,11.704206,12.321264,11.478871,11.977715,15.088643,11.789842
64,26.139713,23.350031,24.449736,24.990596,29.220702,24.383132,26.588063,24.109921,29.856910,23.455261
128,45.055823,43.811885,42.316501,43.551035,42.009960,44.254063,45.943373,43.012477,40.020407,41.927400
256,54.893892,54.889112,55.720602,55.524364,54.631447,56.647214,56.776953,54.830693,53.475580,55.846883
512,62.488370,59.342488,67.344632,67.054800,60.678881,60.849120,60.354230,59.253314,65.999748,59.153068

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,1.788707,1.835316,0.310016,1.744058,1.653518,1.742872,1.912211,1.615005,1.419943,1.567640,1.558929
2,1.564420,1.751613,0.865759,1.054150,1.303438,1.427186,1.358437,0.844048,1.346128,1.169333,1.268451
4,1.535863,0.952122,1.804542,1.367897,0.551359,1.186360,1.403071,1.554973,1.266190,1.579272,1.320165
8,3.570290,2.295078,4.351193,3.951478,2.589362,2.654099,3.943084,2.791604,2.586352,1.617543,3.035008
16,6.040426,6.186261,8.021230,6.112882,6.946717,9.118275,4.658300,5.448931,8.639873,7.551356,6.872425
32,14.254376,15.860700,12.714943,12.028179,11.704206,12.321264,11.478871,11.977715,15.088643,11.789842,12.921874
64,26.139713,23.350031,24.449736,24.990596,29.220702,24.383132,26.588063,24.109921,29.856910,23.455261,25.654407
128,45.055823,43.811885,42.316501,43.551035,42.009960,44.254063,45.943373,43.012477,40.020407,41.927400,43.190293
256,54.893892,54.889112,55.720602,55.524364,54.631447,56.647214,56.776953,54.830693,53.475580,55.846883,55.323674
512,62.488370,59.342488,67.344632,67.054800,60.678881,60.849120,60.354230,59.253314,65.999748,59.153068,62.251865

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")