In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/c3-highcpu-8'
SCENARIO = 'c3-highcpu-8'
NETWORK_LATENCY = 0.028245

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

0.2688135

In [5]:
print(dfs[1][1].latency.to_string(index=False))

0.323687
0.213940

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.214543,0.290010,0.173691,0.230709,0.222815,0.175888,0.234277,0.208266,0.186382,0.185571
2,0.137538,0.268813,0.273731,0.263335,0.166160,0.181032,0.164268,0.143108,0.217801,0.247035
4,0.616158,0.849448,1.441286,0.793023,0.187139,0.384398,0.418446,0.649654,0.371973,1.371044
8,0.780047,1.098156,0.828946,1.086622,1.024898,0.607993,1.146466,0.577534,1.099449,0.901006
16,1.038713,1.152441,1.352312,0.930133,1.163157,1.427137,1.159420,1.515512,1.016722,1.161060
32,1.669728,2.092777,1.996138,1.635671,1.585801,1.857699,1.565730,1.915403,1.896676,1.755589
64,3.321818,3.398846,3.421793,3.250688,3.731615,3.011001,3.293171,3.437984,3.905594,3.181020
128,6.519440,6.701491,6.636724,6.961619,6.185274,6.736394,7.055098,6.552098,6.121224,6.926267
256,12.764710,12.686782,12.968344,12.755167,12.127765,12.453727,12.617733,12.814354,12.133637,12.874418
512,36.035321,29.192809,33.286436,31.237897,33.511599,37.483453,28.310039,28.394829,29.159614,28.308363

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.186298,0.261765,0.145446,0.202464,0.194570,0.147643,0.206032,0.180021,0.158137,0.157326
2,0.109293,0.240568,0.245486,0.235090,0.137915,0.152787,0.136023,0.114864,0.189556,0.218790
4,0.587913,0.821203,1.413041,0.764778,0.158894,0.356153,0.390201,0.621409,0.343728,1.342799
8,0.751802,1.069911,0.800701,1.058377,0.996653,0.579748,1.118221,0.549289,1.071204,0.872761
16,1.010468,1.124196,1.324067,0.901888,1.134912,1.398892,1.131175,1.487267,0.988477,1.132815
32,1.641483,2.064532,1.967893,1.607426,1.557556,1.829454,1.537485,1.887158,1.868431,1.727344
64,3.293573,3.370601,3.393548,3.222443,3.703370,2.982756,3.264926,3.409739,3.877349,3.152775
128,6.491195,6.673246,6.608479,6.933374,6.157029,6.708149,7.026853,6.523853,6.092979,6.898022
256,12.736465,12.658537,12.940099,12.726922,12.099520,12.425482,12.589488,12.786109,12.105392,12.846173
512,36.007076,29.164564,33.258191,31.209652,33.483354,37.455208,28.281794,28.366584,29.131369,28.280118

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,0.186298,0.261765,0.145446,0.202464,0.194570,0.147643,0.206032,0.180021,0.158137,0.157326,0.183970
2,0.109293,0.240568,0.245486,0.235090,0.137915,0.152787,0.136023,0.114864,0.189556,0.218790,0.178037
4,0.587913,0.821203,1.413041,0.764778,0.158894,0.356153,0.390201,0.621409,0.343728,1.342799,0.680012
8,0.751802,1.069911,0.800701,1.058377,0.996653,0.579748,1.118221,0.549289,1.071204,0.872761,0.886867
16,1.010468,1.124196,1.324067,0.901888,1.134912,1.398892,1.131175,1.487267,0.988477,1.132815,1.163415
32,1.641483,2.064532,1.967893,1.607426,1.557556,1.829454,1.537485,1.887158,1.868431,1.727344,1.768876
64,3.293573,3.370601,3.393548,3.222443,3.703370,2.982756,3.264926,3.409739,3.877349,3.152775,3.367108
128,6.491195,6.673246,6.608479,6.933374,6.157029,6.708149,7.026853,6.523853,6.092979,6.898022,6.611318
256,12.736465,12.658537,12.940099,12.726922,12.099520,12.425482,12.589488,12.786109,12.105392,12.846173,12.591419
512,36.007076,29.164564,33.258191,31.209652,33.483354,37.455208,28.281794,28.366584,29.131369,28.280118,31.463791

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")