In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/c3-highcpu-4'
SCENARIO = 'c3-highcpu-4'
NETWORK_LATENCY = 0.028315

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

1.209297

In [5]:
print(dfs[1][1].latency.to_string(index=False))

1.377706
1.040888

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,1.247303,1.231479,1.181993,1.350558,1.427586,1.249021,1.377070,1.245651,1.246154,1.159081
2,0.944101,1.209297,1.219454,1.137447,1.058843,1.050680,1.029929,1.023451,1.211752,1.124507
4,0.850500,0.763858,1.134940,0.801346,0.692998,0.511815,0.556482,0.817317,0.758314,0.803219
8,1.238923,1.076472,1.284277,1.221122,1.065688,0.675476,1.154801,0.858353,1.217100,1.357005
16,2.297992,2.193581,2.997503,1.868608,1.919720,3.000332,3.032787,3.316238,2.322688,2.542315
32,4.149243,5.388691,4.053629,4.674913,4.663566,5.033782,4.677662,5.253452,4.325682,4.555707
64,8.678844,7.857339,8.297714,8.021737,10.134886,6.662775,6.971577,8.999760,9.007597,8.693769
128,16.638529,16.099125,14.629583,16.799833,15.716332,18.507790,17.493600,17.142149,18.487720,17.178575
256,34.824990,35.088711,30.312088,32.704080,32.706610,30.520309,35.273378,34.274612,32.409105,34.079084
512,47.338134,45.580348,51.736043,47.158732,49.283548,50.326290,47.947353,48.214688,47.412678,46.311705

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,1.218988,1.203164,1.153678,1.322243,1.399271,1.220706,1.348755,1.217336,1.217839,1.130766
2,0.915786,1.180982,1.191139,1.109132,1.030528,1.022365,1.001613,0.995136,1.183437,1.096192
4,0.822185,0.735543,1.106625,0.773031,0.664683,0.483500,0.528168,0.789002,0.729999,0.774904
8,1.210608,1.048157,1.255962,1.192807,1.037373,0.647161,1.126486,0.830038,1.188785,1.328690
16,2.269677,2.165266,2.969188,1.840293,1.891405,2.972017,3.004472,3.287923,2.294373,2.514000
32,4.120928,5.360376,4.025314,4.646598,4.635251,5.005467,4.649347,5.225137,4.297367,4.527392
64,8.650529,7.829024,8.269399,7.993422,10.106571,6.634460,6.943262,8.971445,8.979282,8.665454
128,16.610214,16.070810,14.601268,16.771518,15.688017,18.479475,17.465285,17.113834,18.459405,17.150260
256,34.796675,35.060396,30.283773,32.675765,32.678295,30.491994,35.245063,34.246297,32.380790,34.050769
512,47.309819,45.552033,51.707728,47.130417,49.255233,50.297975,47.919038,48.186373,47.384363,46.283390

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,1.218988,1.203164,1.153678,1.322243,1.399271,1.220706,1.348755,1.217336,1.217839,1.130766,1.243275
2,0.915786,1.180982,1.191139,1.109132,1.030528,1.022365,1.001613,0.995136,1.183437,1.096192,1.072631
4,0.822185,0.735543,1.106625,0.773031,0.664683,0.483500,0.528168,0.789002,0.729999,0.774904,0.740764
8,1.210608,1.048157,1.255962,1.192807,1.037373,0.647161,1.126486,0.830038,1.188785,1.328690,1.086607
16,2.269677,2.165266,2.969188,1.840293,1.891405,2.972017,3.004472,3.287923,2.294373,2.514000,2.520861
32,4.120928,5.360376,4.025314,4.646598,4.635251,5.005467,4.649347,5.225137,4.297367,4.527392,4.649318
64,8.650529,7.829024,8.269399,7.993422,10.106571,6.634460,6.943262,8.971445,8.979282,8.665454,8.304285
128,16.610214,16.070810,14.601268,16.771518,15.688017,18.479475,17.465285,17.113834,18.459405,17.150260,16.841009
256,34.796675,35.060396,30.283773,32.675765,32.678295,30.491994,35.245063,34.246297,32.380790,34.050769,33.190982
512,47.309819,45.552033,51.707728,47.130417,49.255233,50.297975,47.919038,48.186373,47.384363,46.283390,48.102637

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")