In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/standard-nc4as-t4-v3'
SCENARIO = 'standard-nc4as-t4-v3'
NETWORK_LATENCY = 0.026086

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

0.116361

In [5]:
print(dfs[1][1].latency.to_string(index=False))

0.120468
0.112254

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.216977,0.216155,0.185154,0.227377,0.197527,0.202393,0.222397,0.201881,0.214542,0.196014
2,0.080283,0.116361,0.114654,0.107360,0.078537,0.083063,0.082804,0.076649,0.095007,0.094076
4,0.166612,0.128245,0.145688,0.136693,0.083084,0.114438,0.115409,0.141698,0.119500,0.154217
8,0.183801,0.180156,0.181879,0.199716,0.154280,0.124040,0.162754,0.149078,0.196986,0.205956
16,0.228219,0.242636,0.263413,0.206101,0.261660,0.267606,0.227507,0.302224,0.259810,0.260852
32,0.352879,0.411574,0.384787,0.322222,0.311328,0.352755,0.322617,0.319182,0.376871,0.342360
64,0.534490,0.518148,0.529951,0.488334,0.564765,0.498081,0.498138,0.524856,0.591725,0.501417
128,0.886210,0.837764,0.872167,0.886887,0.873521,0.904352,0.955837,0.840554,0.778144,0.895278
256,1.526236,1.538161,1.467911,1.514197,1.430964,1.385637,1.484615,1.487906,1.464773,1.554366
512,2.487216,2.850755,2.456872,2.452605,2.524789,2.649434,2.492867,2.593851,3.761860,2.568895

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.190891,0.190069,0.159068,0.201291,0.171441,0.176307,0.196311,0.175795,0.188456,0.169928
2,0.054197,0.090275,0.088568,0.081274,0.052451,0.056977,0.056718,0.050563,0.068921,0.067990
4,0.140526,0.102159,0.119602,0.110607,0.056998,0.088352,0.089323,0.115612,0.093414,0.128131
8,0.157715,0.154070,0.155793,0.173630,0.128194,0.097954,0.136668,0.122992,0.170900,0.179870
16,0.202133,0.216550,0.237327,0.180015,0.235574,0.241520,0.201421,0.276138,0.233724,0.234766
32,0.326793,0.385488,0.358701,0.296136,0.285242,0.326669,0.296531,0.293096,0.350785,0.316274
64,0.508404,0.492062,0.503865,0.462248,0.538679,0.471995,0.472052,0.498770,0.565639,0.475331
128,0.860124,0.811678,0.846081,0.860801,0.847435,0.878266,0.929751,0.814468,0.752058,0.869192
256,1.500150,1.512074,1.441825,1.488111,1.404878,1.359551,1.458529,1.461820,1.438687,1.528280
512,2.461130,2.824669,2.430786,2.426519,2.498703,2.623348,2.466781,2.567765,3.735774,2.542809

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,0.190891,0.190069,0.159068,0.201291,0.171441,0.176307,0.196311,0.175795,0.188456,0.169928,0.181956
2,0.054197,0.090275,0.088568,0.081274,0.052451,0.056977,0.056718,0.050563,0.068921,0.067990,0.066793
4,0.140526,0.102159,0.119602,0.110607,0.056998,0.088352,0.089323,0.115612,0.093414,0.128131,0.104472
8,0.157715,0.154070,0.155793,0.173630,0.128194,0.097954,0.136668,0.122992,0.170900,0.179870,0.147779
16,0.202133,0.216550,0.237327,0.180015,0.235574,0.241520,0.201421,0.276138,0.233724,0.234766,0.225917
32,0.326793,0.385488,0.358701,0.296136,0.285242,0.326669,0.296531,0.293096,0.350785,0.316274,0.323571
64,0.508404,0.492062,0.503865,0.462248,0.538679,0.471995,0.472052,0.498770,0.565639,0.475331,0.498904
128,0.860124,0.811678,0.846081,0.860801,0.847435,0.878266,0.929751,0.814468,0.752058,0.869192,0.846985
256,1.500150,1.512074,1.441825,1.488111,1.404878,1.359551,1.458529,1.461820,1.438687,1.528280,1.459391
512,2.461130,2.824669,2.430786,2.426519,2.498703,2.623348,2.466781,2.567765,3.735774,2.542809,2.657828

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")