In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/n1-standard-8'
SCENARIO = 'n1-standard-8'
NETWORK_LATENCY = 0.053863

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

0.166947

In [5]:
print(dfs[1][1].latency.to_string(index=False))

0.179428
0.154466

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.235365,0.246495,0.222831,0.238301,0.236571,0.224200,0.241572,0.254098,0.234818,0.234941
2,0.130431,0.166947,0.173414,0.170228,0.134915,0.137673,0.142578,0.132046,0.157581,0.155961
4,0.225045,0.195158,0.215880,0.214210,0.141375,0.167012,0.159231,0.210172,0.191888,0.203792
8,0.230965,0.242641,0.230392,0.252024,0.210045,0.193450,0.229436,0.222588,0.234894,0.210679
16,0.325259,0.326998,0.355471,0.288197,0.328092,0.345374,0.298898,0.373997,0.356689,0.344604
32,0.418847,0.435293,0.417819,0.416008,0.399434,0.451536,0.380583,0.421589,0.410410,0.419428
64,0.596660,0.596681,0.605140,0.621798,0.630265,0.612349,0.613025,0.605148,0.667337,0.569966
128,1.060772,1.018323,1.004038,1.100490,1.029473,1.094443,1.117075,0.967977,0.942562,1.026447
256,1.810112,1.773426,1.783426,1.725784,1.701578,1.636806,1.686730,1.698411,1.674417,1.711857
512,2.951865,2.945351,2.939241,2.966418,2.908398,3.079431,2.946920,2.872186,3.076264,2.879335

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.181502,0.192632,0.168968,0.184438,0.182708,0.170337,0.187709,0.200235,0.180955,0.181078
2,0.076568,0.113084,0.119552,0.116365,0.081052,0.083810,0.088716,0.078183,0.103718,0.102098
4,0.171182,0.141295,0.162017,0.160348,0.087512,0.113149,0.105369,0.156309,0.138025,0.149929
8,0.177102,0.188778,0.176529,0.198161,0.156183,0.139587,0.175573,0.168725,0.181031,0.156816
16,0.271396,0.273135,0.301609,0.234334,0.274229,0.291511,0.245035,0.320134,0.302826,0.290741
32,0.364984,0.381430,0.363956,0.362145,0.345571,0.397673,0.326720,0.367726,0.356547,0.365565
64,0.542797,0.542818,0.551277,0.567935,0.576402,0.558486,0.559162,0.551285,0.613474,0.516103
128,1.006909,0.964460,0.950175,1.046627,0.975610,1.040580,1.063212,0.914114,0.888699,0.972584
256,1.756249,1.719563,1.729563,1.671921,1.647715,1.582943,1.632867,1.644548,1.620554,1.657994
512,2.898002,2.891488,2.885378,2.912555,2.854535,3.025568,2.893057,2.818323,3.022401,2.825472

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,0.181502,0.192632,0.168968,0.184438,0.182708,0.170337,0.187709,0.200235,0.180955,0.181078,0.183056
2,0.076568,0.113084,0.119552,0.116365,0.081052,0.083810,0.088716,0.078183,0.103718,0.102098,0.096314
4,0.171182,0.141295,0.162017,0.160348,0.087512,0.113149,0.105369,0.156309,0.138025,0.149929,0.138513
8,0.177102,0.188778,0.176529,0.198161,0.156183,0.139587,0.175573,0.168725,0.181031,0.156816,0.171848
16,0.271396,0.273135,0.301609,0.234334,0.274229,0.291511,0.245035,0.320134,0.302826,0.290741,0.280495
32,0.364984,0.381430,0.363956,0.362145,0.345571,0.397673,0.326720,0.367726,0.356547,0.365565,0.363232
64,0.542797,0.542818,0.551277,0.567935,0.576402,0.558486,0.559162,0.551285,0.613474,0.516103,0.557974
128,1.006909,0.964460,0.950175,1.046627,0.975610,1.040580,1.063212,0.914114,0.888699,0.972584,0.982297
256,1.756249,1.719563,1.729563,1.671921,1.647715,1.582943,1.632867,1.644548,1.620554,1.657994,1.666392
512,2.898002,2.891488,2.885378,2.912555,2.854535,3.025568,2.893057,2.818323,3.022401,2.825472,2.902678

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")