In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/n1-standard-4'
SCENARIO = 'n1-standard-4'
NETWORK_LATENCY = 0.054032

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

0.6996635

In [5]:
print(dfs[1][1].latency.to_string(index=False))

1.175283
0.224044

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,1.337969,1.467205,1.332093,1.381071,1.326077,1.318085,1.290215,1.255629,1.326349,1.268163
2,0.628630,0.699663,1.021756,1.073341,0.970211,1.047191,1.000217,1.009853,0.725346,0.681511
4,0.690354,0.699870,0.318316,0.468915,0.380317,0.492512,0.413717,0.504263,0.612273,0.666431
8,0.275798,0.252319,0.378427,0.291448,0.263943,0.252460,0.285686,0.255297,0.317352,0.296747
16,0.361123,0.419361,0.388070,0.336137,0.351316,0.430886,0.351739,0.423243,0.365910,0.396920
32,0.474503,0.569624,0.527256,0.470542,0.460820,0.513971,0.482438,0.485054,0.520799,0.497015
64,0.838513,0.781387,0.825861,0.816059,0.845468,0.780755,0.796968,0.804753,0.871429,0.754212
128,1.427941,1.385097,1.394394,1.420081,1.378584,1.444006,1.561839,1.325944,1.374256,1.450675
256,2.545685,2.478408,2.618145,2.549507,2.404890,2.522964,2.484251,2.453722,2.394031,2.543379
512,4.048631,4.481569,4.150317,4.175313,4.303863,4.425045,4.311652,4.316271,4.440461,4.469377

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,1.283937,1.413173,1.278061,1.327039,1.272045,1.264053,1.236183,1.201597,1.272317,1.214131
2,0.574599,0.645632,0.967724,1.019309,0.916179,0.993159,0.946186,0.955821,0.671314,0.627479
4,0.636322,0.645838,0.264284,0.414883,0.326285,0.438480,0.359685,0.450231,0.558241,0.612399
8,0.221766,0.198287,0.324395,0.237416,0.209911,0.198428,0.231654,0.201265,0.263320,0.242715
16,0.307091,0.365329,0.334038,0.282105,0.297284,0.376854,0.297707,0.369211,0.311878,0.342888
32,0.420471,0.515592,0.473224,0.416510,0.406788,0.459939,0.428406,0.431022,0.466767,0.442983
64,0.784481,0.727355,0.771829,0.762027,0.791436,0.726723,0.742936,0.750721,0.817397,0.700180
128,1.373909,1.331065,1.340362,1.366049,1.324552,1.389974,1.507807,1.271912,1.320224,1.396643
256,2.491653,2.424376,2.564113,2.495475,2.350858,2.468932,2.430219,2.399690,2.339999,2.489347
512,3.994599,4.427537,4.096285,4.121281,4.249831,4.371013,4.257620,4.262239,4.386429,4.415345

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,1.283937,1.413173,1.278061,1.327039,1.272045,1.264053,1.236183,1.201597,1.272317,1.214131,1.276254
2,0.574599,0.645632,0.967724,1.019309,0.916179,0.993159,0.946186,0.955821,0.671314,0.627479,0.831740
4,0.636322,0.645838,0.264284,0.414883,0.326285,0.438480,0.359685,0.450231,0.558241,0.612399,0.470665
8,0.221766,0.198287,0.324395,0.237416,0.209911,0.198428,0.231654,0.201265,0.263320,0.242715,0.232916
16,0.307091,0.365329,0.334038,0.282105,0.297284,0.376854,0.297707,0.369211,0.311878,0.342888,0.328438
32,0.420471,0.515592,0.473224,0.416510,0.406788,0.459939,0.428406,0.431022,0.466767,0.442983,0.446170
64,0.784481,0.727355,0.771829,0.762027,0.791436,0.726723,0.742936,0.750721,0.817397,0.700180,0.757508
128,1.373909,1.331065,1.340362,1.366049,1.324552,1.389974,1.507807,1.271912,1.320224,1.396643,1.362250
256,2.491653,2.424376,2.564113,2.495475,2.350858,2.468932,2.430219,2.399690,2.339999,2.489347,2.445466
512,3.994599,4.427537,4.096285,4.121281,4.249831,4.371013,4.257620,4.262239,4.386429,4.415345,4.258218

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")