In [1]:
import pandas as pd
import numpy as np

In [2]:
BASE_DIR = 'outputs/standard-nc8as-t4-v3'
SCENARIO = 'standard-nc8as-t4-v3'
NETWORK_LATENCY = 0.024775

In [3]:
dfs = []
for i in range(10):
    dfs.append([ pd.read_csv(f'{BASE_DIR}/client-simulation-iter_{i+1}-{2**k}.csv', sep="#") for k in range(10) ])
len(dfs)

10

In [4]:
latency = np.average(dfs[1][1].latency)
latency

0.10705300000000001

In [5]:
print(dfs[1][1].latency.to_string(index=False))

0.120731
0.093375

In [6]:
# latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]+['average']))
latencies = pd.DataFrame(columns=(['sentences']+[*range(1,11)]))
latencies.sentences = pd.Series([ 2**i for i in range(10) ])
latencies = latencies.set_index('sentences')
latencies

             1    2    3    4    5    6    7    8    9   10
sentences
1          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
16         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
32         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
64         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
128        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
256        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
512        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

In [7]:
for i in range(10):
    latencies[i+1] = pd.Series([ np.nanmean(dfs[i][k].latency) for k in range(10) ], index=latencies.index)
# latencies.average = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.115677,0.126182,0.101441,0.113837,0.117070,0.105355,0.112055,0.110361,0.098624,0.098205
2,0.075391,0.107053,0.114608,0.101370,0.074400,0.084232,0.080536,0.070478,0.095445,0.094406
4,0.161233,0.132232,0.153139,0.159347,0.085925,0.113004,0.104676,0.147685,0.129881,0.145868
8,0.166812,0.145640,0.163638,0.203460,0.151282,0.125747,0.160719,0.154487,0.178556,0.160491
16,0.237675,0.229500,0.249331,0.213528,0.269714,0.265210,0.243524,0.276356,0.260362,0.250008
32,0.329055,0.371233,0.368163,0.323799,0.304948,0.350104,0.304622,0.341084,0.332949,0.322745
64,0.522885,0.507124,0.501545,0.529614,0.543116,0.488030,0.544714,0.506349,0.595952,0.477079
128,0.882396,0.829017,0.902002,0.844009,0.847539,0.867555,0.896013,0.888944,0.768061,0.875638
256,1.512346,1.479043,1.449799,1.463771,1.513950,1.447223,1.451438,1.512154,1.402778,1.496773
512,9.452533,6.639840,8.615017,7.836191,9.282043,9.438121,9.338001,8.400750,10.154749,8.607356

In [8]:
latencies = latencies - NETWORK_LATENCY
latencies

,1,2,3,4,5,6,7,8,9,10
sentences,,,,,,,,,,
1,0.090902,0.101407,0.076666,0.089062,0.092295,0.080580,0.087280,0.085586,0.073849,0.073430
2,0.050616,0.082278,0.089833,0.076595,0.049625,0.059457,0.055761,0.045703,0.070670,0.069631
4,0.136458,0.107457,0.128364,0.134572,0.061150,0.088229,0.079901,0.122910,0.105106,0.121093
8,0.142037,0.120865,0.138864,0.178685,0.126507,0.100972,0.135944,0.129712,0.153781,0.135716
16,0.212900,0.204725,0.224556,0.188753,0.244939,0.240435,0.218749,0.251581,0.235587,0.225233
32,0.304280,0.346458,0.343388,0.299024,0.280173,0.325329,0.279847,0.316309,0.308174,0.297970
64,0.498110,0.482349,0.476770,0.504839,0.518341,0.463255,0.519939,0.481574,0.571177,0.452304
128,0.857621,0.804242,0.877227,0.819234,0.822764,0.842780,0.871238,0.864169,0.743286,0.850863
256,1.487571,1.454268,1.425024,1.438996,1.489175,1.422448,1.426663,1.487379,1.378003,1.471998
512,9.427758,6.615065,8.590242,7.811416,9.257268,9.413346,9.313226,8.375975,10.129974,8.582581

In [9]:
latencies['average'] = latencies.aggregate('mean', axis=1)
latencies

,1,2,3,4,5,6,7,8,9,10,average
sentences,,,,,,,,,,,
1,0.090902,0.101407,0.076666,0.089062,0.092295,0.080580,0.087280,0.085586,0.073849,0.073430,0.085106
2,0.050616,0.082278,0.089833,0.076595,0.049625,0.059457,0.055761,0.045703,0.070670,0.069631,0.065017
4,0.136458,0.107457,0.128364,0.134572,0.061150,0.088229,0.079901,0.122910,0.105106,0.121093,0.108524
8,0.142037,0.120865,0.138864,0.178685,0.126507,0.100972,0.135944,0.129712,0.153781,0.135716,0.136308
16,0.212900,0.204725,0.224556,0.188753,0.244939,0.240435,0.218749,0.251581,0.235587,0.225233,0.224746
32,0.304280,0.346458,0.343388,0.299024,0.280173,0.325329,0.279847,0.316309,0.308174,0.297970,0.310095
64,0.498110,0.482349,0.476770,0.504839,0.518341,0.463255,0.519939,0.481574,0.571177,0.452304,0.496866
128,0.857621,0.804242,0.877227,0.819234,0.822764,0.842780,0.871238,0.864169,0.743286,0.850863,0.835343
256,1.487571,1.454268,1.425024,1.438996,1.489175,1.422448,1.426663,1.487379,1.378003,1.471998,1.448153
512,9.427758,6.615065,8.590242,7.811416,9.257268,9.413346,9.313226,8.375975,10.129974,8.582581,8.751685

In [10]:
latencies.to_csv(f'{BASE_DIR}/results_client_data-{SCENARIO}.csv', index=True, sep=",")